- name: "install ntpd"
  pacman:
    name: ntp
    state: installed
  notify: "restart ntpd"
  tags: ntp

- name: "conifgure ntpd"
  template:
    src: "ntp.conf.j2"
    dest: "/etc/ntp.conf"
  notify: "restart ntpd"
  tags: ntp

- meta: flush_handlers
  tags: ntp
