- name: "install nginx"
  pacman: name=nginx state=present
  notify: "restart nginx"
  tags: nginx

- name: "put configuration files"
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf backup=yes
  copy: src={{ item.src }} dest={{ item.dest }} backup=yes
  with_items:
  - src: nginx.conf
    dest: /etc/nginx/nginx.conf
  - src: tls_params
    dest: /etc/nginx/tls_params
  notify: "restart nginx"
  tags: nginx

- name: "create servers directory"
  file: name=/etc/nginx/servers state=directory
  notify: "restart nginx"
  tags: nginx

- name: "create servers"
  copy: src={{ item }}.conf dest=/etc/nginx/servers
  with_items: servers
  notify: "restart nginx"
  tags: nginx

- meta: flush_handlers
  tags: nginx
