---
- name: "install nginx"
  pacman: name=nginx state=present
- name: "enable and start nginx"
  service: name=nginx.service enabled=yes state=started
- name: "put configuration file"
  template:
  args:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    backup: yes
  notify: "restart nginx"

