- name: "install nginx"
  pacman: name=nginx state=present
  notify: "restart nginx"
  tags: nginx

- name: "put configuration file"
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf backup=yes
  notify: "restart nginx"
  tags: nginx

- name: "create servers directory"
  file: name=/etc/nginx/servers state=directory
  notify: "restart nginx"
  tags: nginx

- name: "create servers"
  copy: src={{ item }}.conf dest=/etc/nginx/servers
  with_items: servers
  notify: "restart nginx"
  tags: nginx

- meta: flush_handlers
  tags: nginx
