- name: "create wheel group"
  group: name=wheel state=present
  tags: accounts

- name: "create groups"
  group: name={{ item.name }} gid={{ item.gid }} state=present
  with_items: account.groups
  tags: accounts

- name: "create users"
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    group: "{{ item.group }}"
    groups: "{{ item.groups }}"
    system: "{{ item.system }}"
    createhome: "{{ (item.system == \"yes\") | ternary('no', 'yes') }}"
    comment: "{{ item.comment }}"
    state: "present"
  with_items: account.users
  tags: accounts

- name: "allow sudo to wheel users"
  lineinfile:
    line: "%wheel ALL=(ALL) ALL"
    dest: "/etc/sudoers.d/wheel"
    create: yes
  tags: accounts

# name: "ensure .ssh exists"

- name: "set authorized keys"
  authorized_key: user={{ item.0.user}} state=present manage_dir=yes
  args:
    key: "{{ secrets.ssh[item.1] }}"
  with_subelements: [ account.authorized_keys, pubkeys ]
  tags: accounts

- name: "install ssh config file"
  copy: dest=~{{ item.user }}/.ssh/config owner={{ item.user }} group={{ item.user }} mode=0600
  args:
    content: "{{ secrets.ssh_config }}"
  with_items: account.authorized_keys
  tags: accounts

- name: "disable ssh password login"
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    line: "PasswordAuthentication no"
    regexp: "^#?PasswordAuthentication (?:yes|no)$"
  notify: "restart sshd"
  tags: accounts

- name: "disable password login for root"
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    line: "PermitRootLogin without-password"
    regexp: "^#?PermitRootLogin (?:yes|no|without-password)$"
  notify: "restart sshd"
  tags: accounts

- name: "flush handlers"
  meta: flush_handlers
  tags: accounts
