- name: "create wheel group"
  group: name=wheel state=present
  tags: accounts

- name: "create users"
  user: name={{ item.name }} groups={{ item.groups }}
  args:
    comment: "{{ item.comment }}"
  with_items: users
  tags: accounts

- name: "allow sudo to wheel users"
  lineinfile:
    line: "%wheel ALL=(ALL) ALL"
    dest: "/etc/sudoers.d/wheel"
    create: yes
  tags: accounts

- name: "set authorized keys"
  authorized_key: user={{ item.0.user}} state=present manage_dir=yes
  args:
    key: "{{ secrets.ssh[item.1] }}"
  with_subelements: [ authorized_keys, pubkeys ]
  tags: accounts

- name: "install ssh config file"
  copy: dest=~{{ item.user }}/.ssh/config owner={{ item.user }} group={{ item.user }} mode=0600
  args:
    content: "{{ secrets.ssh_config }}"
  with_items: authorized_keys
  tags: accounts

- name: "disable ssh password login"
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    line: "PasswordAuthentication no"
    regexp: "^#?PasswordAuthentication (?:yes|no)$"
  notify: "restart sshd"
  tags: accounts

- name: "flush handlers"
  meta: flush_handlers
  tags: accounts
