- name: "install haproxy"
  pacman:
    name: haproxy
    state: present
  notify: "restart haproxy"
  tags: haproxy

- name: "create haproxy directory"
  file:
    name: "/var/lib/haproxy"
    state: directory
    owner: haproxy
    group: haproxy
    mode: "700"
  notify: "restart haproxy"
  tags: haproxy

- name: "configure haproxy"
  copy:
    src: "haproxy.cfg"
    dest: "/etc/haproxy/haproxy.cfg"
  notify: "restart haproxy"
  tags: haproxy


