- name: "{{ name }} | reload systemd units"
  shell: systemctl daemon-reload

- name: "{{ name }} | restart"
  service:
    name: "{{ svc['update'].name }}"
    enabled: yes
    state: "{{ svc['update'].state }}"
