- name: "{{ name }} | reload systemd units"
  shell: systemctl daemon-reload
  tags: python2-app

- name: "{{ name }} | restart services"
  service: name={{ item.name }} enabled=yes state={{ item.state }}
  with_items: update
  tags: python2-app
