- name: basic arch configuration
  hosts: [config, server, workstation, mediacenter]
  vars_files: [secrets.yml]

  roles:

  - role: accounts
    account:
      groups:
      - { name: jjm,   gid: 1000 }
      - { name: usb2t, gid: 60000 }
      users:
      - { name: jjm,   uid: 1000,  group: "jjm",   comment: "Joost Molenaar", groups: "usb2t,users,wheel", system: false }
      - { name: usb2t, uid: 60000, group: "usb2t", comment: ~,                groups: ~,                   system: true }
      authorized_keys:
      - { user: root, pubkeys: [ j.j.molenaar@gmail.com, jjm@nexus5, joost@ws-nuc68 ] }
      - { user: jjm,  pubkeys: [ j.j.molenaar@gmail.com, jjm@nexus5, joost@ws-nuc68 ] }

  - role: ntp
    servers:
    - ntp.xs4all.nl

- name: odds and ends
  hosts: [config, server, workstation, mediacenter]
  tasks:
  - name: "systemd symlinks"
    file: dest={{ item.dest }} src={{ item.src }} state=link
    with_items:
    - { dest: "/usr/local/bin/sc", src: "/usr/bin/systemctl" }
    - { dest: "/usr/local/bin/jc", src: "/usr/bin/journalctl" }
    tags: packages
