- name: server configuration
  hosts: [server]
  vars_files: [secrets.yml]
  roles:
  - role: packages
    packages:
    - dnsutils
    - ethtool
    - graphviz
    - htop
    - inotify-tools
    - libjpeg-turbo
    - libmariadbclient
    - libpng
    - libtiff
    - libxml2
    - libxslt
    - mc
    - mono
    - nmap
    - rsync
    - strace
    - sudo
    - tcpdump
    - tmux
    - traceroute
    - vim-minimal
    - unzip
    - wol

  - role: data
    vault_files:
    - { dest: "/etc/ssl/private/j0057.nl.crt",          mode: "0644", owner: root, group: root, template: secret_plaintext.j2, key: "ssl_j0057_nl_crt" }
    - { dest: "/etc/ssl/private/j0057.nl.chained.crt",  mode: "0644", owner: root, group: root, template: secret_plaintext.j2, key: "ssl_j0057_nl_chained_crt" }
    - { dest: "/etc/ssl/private/j0057.nl.key",          mode: "0600", owner: root, group: root, template: secret_plaintext.j2, key: "ssl_j0057_nl_key" }
    - { dest: "/etc/ssl/private/dev.j0057.nl.crt",      mode: "0644", owner: root, group: root, template: secret_plaintext.j2, key: "ssl_dev_j0057_nl_crt" }
    - { dest: "/etc/ssl/private/dev.j0057.nl.key",      mode: "0600", owner: root, group: root, template: secret_plaintext.j2, key: "ssl_dev_j0057_nl_key" }
    - { dest: "/etc/ssl/private/punosqnp.nl.crt",       mode: "0644", owner: root, group: root, template: secret_plaintext.j2, key: "ssl_punosqnp_nl_crt" }
    - { dest: "/etc/ssl/private/punosqnp.nl.key",       mode: "0600", owner: root, group: root, template: secret_plaintext.j2, key: "ssl_punosqnp_nl_key" }

  - role: build-client
    path:
      aur: "/var/lib/aur_x86_64"
      pkg: "/var/lib/pypkg27"

  - role: nginx
    servers:
    - nl.j0057
    - nl.j0057.dev
    - nl.j0057.www
    - nl.punosqnp
    - nl.punosqnp.www
    - nl.stomrin
    - nl.stomrin.www

  - role: firewall
    iptables:
      chains:
        filter: [allow, fail2ban, geoblocks, spam]

      filter: |
        .. -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT -m comment --comment "established-traffic"

           -A INPUT -j allow
           -A INPUT -j spam
           -A INPUT -j fail2ban
           -A INPUT -j geoblocks

        -4 -A INPUT -p udp --sport 53 -j ACCEPT -m comment --comment dns-answers
        -4 -A INPUT -s 127.0.0.0/8 -d 127.0.0.0/8 -j ACCEPT -m comment --comment "local"
        -4 -A INPUT -p icmp -j ACCEPT -m comment --comment allow-icmp
        -6 -A INPUT -s ff02::/16 -p icmpv6 -j ACCEPT -m comment --comment "link-local-multicast-icmp"
        -6 -A INPUT -s ff80::/10 -p icmpv6 -j ACCEPT -m comment --comment "link-local-icmp"

           -A INPUT -m limit --limit 1/sec -j LOG --log-prefix "[DROP] "
           -A INPUT -j DROP

           -A allow -p tcp --dport 22 -m state --state NEW -j ACCEPT -m comment --comment "tcp/ssh"
           -A allow -p tcp --dport 25 -m state --state NEW -j ACCEPT -m comment --comment "tcp/smtp"
           -A allow -p tcp --dport 53 -m state --state NEW -j ACCEPT -m comment --comment "tcp/dns"
           -A allow -p tcp --dport 80 -m state --state NEW -j ACCEPT -m comment --comment "tcp/http"
           -A allow -p tcp --dport 110 -m state --state NEW -j ACCEPT -m comment --comment "tcp/pop3"
           -A allow -p tcp --dport 111 -m state --state NEW -j ACCEPT -m comment --comment "tcp/nfs/portmap"
           -A allow -p tcp --dport 139 -m state --state NEW -j ACCEPT -m comment --comment "tcp/netbios/1"
           -A allow -p tcp --dport 143 -m state --state NEW -j ACCEPT -m comment --comment "tcp/imap"
           -A allow -p tcp --dport 443 -m state --state NEW -j ACCEPT -m comment --comment "tcp/https"
           -A allow -p tcp --dport 445 -m state --state NEW -j ACCEPT -m comment --comment "tcp/netbios/2"
           -A allow -p tcp --dport 465 -m state --state NEW -j ACCEPT -m comment --comment "tcp/smtps"
           -A allow -p tcp --dport 631 -m state --state NEW -j ACCEPT -m comment --comment "tcp/cups"
           -A allow -p tcp --dport 993 -m state --state NEW -j ACCEPT -m comment --comment "tcp/imaps"
           -A allow -p tcp --dport 995 -m state --state NEW -j ACCEPT -m comment --comment "tcp/pop3s"
           -A allow -p tcp --dport 2049 -m state --state NEW -j ACCEPT -m comment --comment "tcp/nfs/nfsd"
           -A allow -p tcp --dport 4614 -m state --state NEW -j ACCEPT -m comment --comment "tcp/bittorrent"
           -A allow -p tcp --dport 5353 -m state --state NEW -j ACCEPT -m comment --comment "tcp/mdns"
           -A allow -p tcp --dport 9091 -m state --state NEW -j ACCEPT -m comment --comment "tcp/transmission"
           -A allow -p tcp --dport 20048 -m state --state NEW -j ACCEPT -m comment --comment "tcp/nfs/mountd"
           -A allow -p tcp --dport 32803 -m state --state NEW -j ACCEPT -m comment --comment "tcp/nfs/lockd"
           -A allow -p tcp --dport 32764:32769 -m state --state NEW -j ACCEPT -m comment --comment "tcp/nfs/*"

           -A allow -p udp --dport 53 -j ACCEPT -m comment --comment "udp/dns"
           -A allow -p udp --dport 67 -j ACCEPT -m comment --comment "udp/dhcp"
           -A allow -p udp --dport 68 -j ACCEPT -m comment --comment "udp/bootp"
           -A allow -p udp --dport 111 -j ACCEPT -m comment --comment "udp/nfs/portmap"
           -A allow -p udp --dport 123 -j ACCEPT -m comment --comment "udp/ntp"
           -A allow -p udp --dport 137 -j ACCEPT -m comment --comment "udp/netbios/1"
           -A allow -p udp --dport 138 -j ACCEPT -m comment --comment "udp/netbios/2"
           -A allow -p udp --dport 2049 -j ACCEPT -m comment --comment "udp/nfs/nfsd"
           -A allow -p udp --dport 5353 -j ACCEPT -m comment --comment "udp/mdns"
           -A allow -p udp --dport 20048 -j ACCEPT -m comment --comment "udp/nfs/mountd"
           -A allow -p udp --dport 32803 -j ACCEPT -m comment --comment "udp/nfs/lockd"
           -A allow -p udp --dport 32764:32769 -j ACCEPT -m comment --comment "udp/nfs/*"

        -4 -A spam -d 255.255.255.255/32 -p udp -m udp --dport 17500 -j DROP -m comment --comment spam-dropbox-1
        -4 -A spam -d 192.168.178.255/32 -p udp -m udp --dport 17500 -j DROP -m comment --comment spam-dropbox-2
        -4 -A spam -d 192.168.178.255/32 -p udp -m udp --dport 8612 -j DROP -m comment --comment spam-canon-driver
        -4 -A spam -s 192.168.178.1/32                    -p tcp -m tcp --dport 14013 -j REJECT --reject-with tcp-reset -m comment --comment "router-spam"
        -6 -A spam -d 2001:980:e8e5:1:2665:11ff:feec:d7f7 -p tcp -m tcp --dport 14013 -j REJECT --reject-with tcp-reset -m comment --comment "router-spam"

      nat: |
        -4 -A PREROUTING -p tcp --dport 9091 -j DNAT --to-destination 10.103.0.66 -m comment --comment "tcp/9091:btvpn"
        -4 -A POSTROUTING -s 10.103.0.0/24 -o net0 -j MASQUERADE -m comment --comment "masquerade-lxc-network"

  - role: geoblocks
    geoblocks_countries: [cn, kz, ru, ph, in, vn]

  - name: fail2ban

  - role: dns
    dnssec: true
    zones:
    - j0057.nl
    - punosqnp.nl

  - role: mariadb

  - role: python2
    path:
      whl: "/var/lib/pypkg27"
      src: "/var/lib/pypkg27"

  - role: python2-app
    name: cachetest
    pkg: cachetest==1.0.dev14
    cfg:
    - { src: "cachetest.yml", dest: "/etc/uwsgi/apps-enabled/cachetest.yml", keys: ~ }
    enable:
    - { name: uwsgi@cachetest.socket, state: started }
    update:
    - { name: uwsgi@cachetest.service, state: stopped }

  - role: python2-app
    name: dns
    pkg: dns==1.0.dev16
    cfg:
    - { src: "dns.yml", dest: "/etc/uwsgi/apps-enabled/dns.yml", keys: ~ }
    enable:
    - { name: uwsgi@dns.socket, state: started }
    update:
    - { name: uwsgi@dns.service, state: stopped }

  - role: python2-app
    name: hello
    pkg: hello==1.2.dev9
    cfg:
    - { src: "hello.yml", dest: "/etc/uwsgi/apps-enabled/hello.yml", key: ~ }
    enable:
    - { name: uwsgi@hello.socket, state: started }
    update:
    - { name: uwsgi@hello.service, state: stopped }

  - role: python2-app
    name: mp3-dev
    pkg: mp3==2.0.dev88
    cfg:
    - { src: "mp3-dev.yml", dest: "/etc/uwsgi/apps-enabled/mp3-dev.yml", key: ~ }
    enable:
    - { name: uwsgi@mp3-dev.socket, state: started }
    update:
    - { name: uwsgi@mp3-dev.service, state: stopped }

  - role: python2-app
    name: musicdb
    pkg: musicdb==1.0.dev51
    cfg:
    - { src: "musicdb.yml", dest: "/etc/uwsgi/apps-enabled/musicdb.yml", key: ~ }
    - { src: "musicdb.ini", dest: "/etc/musicdb.ini",                    key: ~ }
    enable:
    - { name: uwsgi@musicdb.socket, state: started }
    update:
    - { name: uwsgi@musicdb.service, state: stopped }

  - role: python2-app
    name: oauth
    pkg: oauth==1.0.dev89
    cfg:
    - { src: "oauth.yml",      dest: "/etc/uwsgi/apps-enabled/oauth.yml", key: ~ }
    - { src: "secret_json.j2", dest: "/etc/oauth/keys.json",              key: "oauth_keys_json" }
    enable:
    - { name: uwsgi@oauth.socket, state: started }
    update:
    - { name: uwsgi@oauth.service, state: stopped }

  - role: python2-app
    name: stomrin
    pkg: stomrin==1.0.post33
    cfg:
    - { src: "stomrin.yml",     dest: "/etc/uwsgi/apps-enabled/stomrin.yml", key: ~ }
    - { src: "stomrin.service", dest: "/etc/systemd/system/stomrin.service", key: ~ }
    enable:
    - { name: uwsgi@stomrin.socket, state: started }
    - { name: stomrin.service,      state: started }
    update:
    - { name: uwsgi@stomrin.service, state: stopped }
    - { name: stomrin.service,       state: restarted }

  - role: python2-app
    name: twitter
    pkg: twitter==0.1-108-g7253234
    cfg:
    - { src: "twitter.service", dest: "/etc/systemd/system/twitter.service", key: ~ }
    - { src: "secret_json.j2",  dest: "/etc/twitter/casio_f91w.json",        key: "twitter_casio_f91w" }
    - { src: "secret_json.j2",  dest: "/etc/twitter/convertbot.json",        key: "twitter_convertbot" }
    - { src: "secret_json.j2",  dest: "/etc/twitter/deoldehove.json",        key: "twitter_deoldehove" }
    - { src: "secret_json.j2",  dest: "/etc/twitter/grotebroer1.json",       key: "twitter_grotebroer1" }
    - { src: "secret_json.j2",  dest: "/etc/twitter/hetluchtalarm.json",     key: "twitter_hetluchtalarm" }
    - { src: "secret_json.j2",  dest: "/etc/twitter/johndoeveloper.json",    key: "twitter_johndoeveloper" }
    - { src: "secret_json.j2",  dest: "/etc/twitter/maanfase.json",          key: "twitter_maanfase" }
    - { src: "secret_json.j2",  dest: "/etc/twitter/msvlieland.json",        key: "twitter_msvlieland" }
    - { src: "secret_json.j2",  dest: "/etc/twitter/y2k38warning.json",      key: "twitter_y2k38warning" }
    enable:
    - { name: twitter.service, state: stopped }
    update:
    - { name: twitter.service, state: stopped }

  - role: python2-app
    name: xhttptest
    pkg: xhttptest==1.0.dev13
    cfg:
    - { src: "xhttptest.yml", dest: "/etc/uwsgi/apps-enabled/xhttptest.yml", key: ~ }
    enable:
    - { name: uwsgi@xhttptest.socket, state: started }
    update:
    - { name: uwsgi@xhttptest.service, state: stopped }

  - role: email
    postfix:
      aliases:
      - { dest: "jjm", name: "root" }
      - { dest: "jjm", name: "*" }
      virtuals:
      - { user: "jjm", domain: "@j0057.nl" }
      - { user: "jjm", domain: "@punosqnp.nl" }
      main_cf:
        myhostname: j0057.nl
        mydomain: j0057.nl
        mydestination: [j0057.nl, punosqnp.nl, xi.j0057.nl]
        ssl_cert: /etc/ssl/private/j0057.nl.chained.crt
        ssl_key: /etc/ssl/private/j0057.nl.key
    dovecot:
      users:
      - { name: jjm, uid: 1000, gid: 1000, home: /home/jjm }
      ssl_cert: /etc/ssl/private/j0057.nl.chained.crt
      ssl_key: /etc/ssl/private/j0057.nl.key

  - role: fileserver
    fstab:
    - { dev: "LABEL=USB2T", dir: "/mnt/usb2t", fstype: ext4, opts: nofail }
    shares:
    - { name: "music", dir: "/mnt/usb2t/music", uid: "60000", gid: "60000" }
    - { name: "films", dir: "/mnt/usb2t/films", uid: "60000", gid: "60000" }
    - { name: "series", dir: "/mnt/usb2t/series", uid: "60000", gid: "60000" }

- name: container btvpn
  hosts:
  - btvpn2
  vars_files: [secrets.yml]
  roles:
  - role: iptables
    iptables:
      filter: |
        .. -A INPUT -i net0+ -p tcp -m state --state RELATED,ESTABLISHED -j ACCEPT
           -A INPUT -i net0+ -p tcp --dport 22 -m state --state NEW -j ACCEPT
           -A INPUT -i tun0 -p tcp --dport {{ secrets.vpn.vpn1.peer_port }} -m state --state NEW -j ACCEPT
        -6 -A INPUT -p icmpv6 -j ACCEPT -m comment --comment "icmpv6"
           -A INPUT -j LOG --log-prefix "[DROP] " -m limit --limit 1/sec
           -A INPUT -j DROP
        -4 -A OUTPUT -o tun0 -j ACCEPT
        -4 -A OUTPUT -o net0+ -d {{ secrets.vpn.vpn1.ip }}/32 -j ACCEPT
        -4 -A OUTPUT -o net0+ -d 10.103.0.0/24 -j ACCEPT
        -4 -A OUTPUT -o net0+ -d 192.168.178.0/24 -j ACCEPT
        -4 -A OUTPUT -o lo -d 127.0.0.0/8 -j ACCEPT
        -4 -A OUTPUT -j REJECT --reject-with icmp-net-prohibited
        -6 -A OUTPUT -j REJECT --reject-with icmp6-adm-prohibited
  - role: openvpn
    vpn_name: vpn1
  - role: transmission
