- hosts:
  - config
  - server

  vars_files: [secrets.yml]

  roles:

  - role: arch-common

    users:
    - { name: jjm, uid: 1000, gid: 1000, comment: "Joost Molenaar", groups: "wheel" }

    authorized_keys:
    - { user: root, pubkeys: [ j.j.molenaar@gmail.com, jjm@nexus5, joost@ws-nuc41.schoolmaster.nl ] }
    - { user: jjm,  pubkeys: [ j.j.molenaar@gmail.com, jjm@nexus5, joost@ws-nuc41.schoolmaster.nl ] }

    arch_repo:
    - { name: aur_x86_64, url: "file:///var/lib/aur_x86_64" }

    packages: [ rsync, vim-minimal, htop, mc ]

  - role: ntp
    servers: [ "ntp.xs4all.nl" ]

- hosts:
  - server

  vars_files: [secrets.yml]

  roles:

  - role: data
    vault_files:
    - { dest: "/etc/ssl/private/j0057.nl.crt",          mode: "0644", user: root, group: root, content: "{{ ssl['j0057.nl.crt'] }}" }
    - { dest: "/etc/ssl/private/j0057.nl.chained.crt",  mode: "0644", user: root, group: root, content: "{{ ssl['j0057.nl.chained.crt'] }}" }
    - { dest: "/etc/ssl/private/j0057.nl.key",          mode: "0600", user: root, group: root, content: "{{ ssl['j0057.nl.key'] }}" }

  - role: nginx
    servers:
    - nl.j0057
    - nl.j0057.www
    - nl.j0057.dev
    - nl.stomrin
    - nl.stomrin.www

  - role: python2

  - role: firewall

  - role: python2-app
    name: hello
    pkg: hello==1.2-5-g8159f75
    cfg: 
    - { dest: "/etc/uwsgi/apps-enabled/hello.yml", src: "hello.yml", content: ~ }
    svc:
      enable: { name: uwsgi@hello.socket, state: started }
      update: { name: uwsgi@hello.service, state: stopped }
 
  - role: python2-app
    name: mp3-dev
    pkg: mp3==2.0dev-83-g6d2f451
    cfg: 
    - { dest: "/etc/uwsgi/apps-enabled/mp3-dev.yml", src: "mp3-dev.yml", content: ~ }
    svc:
      enable: { name: uwsgi@mp3-dev.socket, state: started }
      update: { name: uwsgi@mp3-dev.service, state: stopped }

  - role: python2-app
    name: twitter
    pkg: twitter==0.1-106-gf16523a
    cfg:
    - { dest: "/etc/systemd/system/twitter.service",    src: "twitter.service", content: ~ }
    - { dest: "/etc/twitter/casio_f91w.json",           src: ~,                 content: "{{ twitter.casio_f91w | to_nice_json }}" }
    - { dest: "/etc/twitter/convertbot.json",           src: ~,                 content: "{{ twitter.convertbot | to_nice_json }}" }
    - { dest: "/etc/twitter/deoldehove.json",           src: ~,                 content: "{{ twitter.deoldehove | to_nice_json }}" }
    - { dest: "/etc/twitter/grotebroer1.json",          src: ~,                 content: "{{ twitter.grotebroer1 | to_nice_json }}" }
    - { dest: "/etc/twitter/hetluchtalarm.json",        src: ~,                 content: "{{ twitter.hetluchtalarm | to_nice_json }}" }
    - { dest: "/etc/twitter/maanfase.json",             src: ~,                 content: "{{ twitter.maanfase | to_nice_json }}" }
    - { dest: "/etc/twitter/msvlieland.json",           src: ~,                 content: "{{ twitter.msvlieland | to_nice_json }}" }
    svc:
      enable: { name: twitter.service, state: started }
      update: { name: twitter.service, state: restarted }

  - role: email
    postfix:
      aliases:
      - { dest: "jjm", name: "root" }
      - { dest: "jjm", name: "*" }
      virtuals:
      - { user: "jjm", domain: "@j0057.nl" }
      - { user: "jjm", domain: "@punosqnp.nl" }
      main_cf:
        myhostname: j0057.nl
        mydomain: j0057.nl
        mydestination: [j0057.nl, punosqnp.nl, arch-vbox]
        ssl_cert: /etc/ssl/certs/j0057.nl.chained.crt
        ssl_key: /etc/ssl/private/j0057.nl.key

    dovecot:
      users:
      - { name: jjm, uid: 1000, gid: 1000, password: mail-password, home: /home/jjm }
      ssl_cert: /etc/ssl/certs/j0057.nl.chained.crt
      ssl_key: /etc/ssl/private/j0057.nl.key

  - role: fileserver
    fstab:
    - { dev: "LABEL=USB2T", dir: "/mnt/usb2t", fstype: ext4, opts: nofail }
    shares:
    - dir: "/mnt/usb2t/music"
      name: "music"
