- name: "install packages"
  pacman: name={{ item }} state=installed
  with_items: packages
  tags: packages

- name: "systemd symlinks"
  file: dest={{ item.dest }} src={{ item.src }} state=link
  with_items:
  - { dest: "/usr/local/bin/sc", src: "/usr/bin/systemctl" }
  - { dest: "/usr/local/bin/jc", src: "/usr/bin/journalctl" }
  tags: packages
