- name: "run postalias"
  shell: postalias /etc/postfix/aliases
  notify: "restart postfix"
  tags: [email, postfix]

- name: "run postmap"
  shell: postmap /etc/postfix/virtual
  notify: "restart postfix"
  tags: [email, postfix]

- name: "restart postfix"
  service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  with_items:
  - postfix.service
  - postgrey.service
  tags: [email, postfix]

- name: "restart dovecot"
  service:
    name: dovecot.service
    enabled: yes
    state: restarted
  tags: [email, dovecot]
