- name: ensure get-pip.py is available
  get_url:
  args:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /root/get-pip.py

- name: ensure pip is installed
  shell: python2.7 /root/get-pip.py
  args:
    creates: /usr/bin/pip

- name: copy .whl files from ~/pypkg27
  #copy: src=~/pypkg27 dest=/root
  synchronize: src=~/pypkg27 dest=/root group=no owner=no

- name: install packages
  pip: "state=latest extra_args='--no-index --find-links=/root/pypkg27' name={{ item }}"
  with_items:
    - pip
    - setuptools
    - setuptools-metadata
    - setuptools-version-command
    - virtualenv
    - wheel
