#
# python, pip, setuptools etc
#

- name: configure pip
  template: src=pip.conf.j2 dest=/etc/pip.conf
  tags: python2

- name: configure virtualenv (1)
  file: dest=/root/.virtualenv state=directory
  tags: python2

- name: configure virtualenv (2)
  file: dest=/root/.virtualenv/virtualenv.ini src=/etc/pip.conf state=link
  tags: python2

- name: install packages
  pip:
    name: "{{ item }}"
    state: latest
    executable: /root/.local/bin/pip2
    extra_args: --user
  with_items:
  - pip
  - setuptools
  - setuptools-metadata
  - setuptools-version-command
  - virtualenv
  - wheel
  - requests
  tags: python2

#
# uwsgi
#

- name: "install uwsgi"
  pacman: name={{ item }} state=present
  with_items:
  - uwsgi
  - uwsgi-plugin-python2
  tags: [python2, uwsgi]

- name: "install config files"
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
  # { src: run_uwsgi.conf,  dest: /etc/tmpfiles.d/run_uwsgi.conf }
  - { src: uwsgi@.service,  dest: /etc/systemd/system/uwsgi@.service }
  - { src: uwsgi@.socket,   dest: /etc/systemd/system/uwsgi@.socket }
  tags: [python2, uwsgi]

- name: "create uwsgi apps-enabled directory"
  file: path=/etc/uwsgi/apps-enabled state=directory
  tags: [python2, uwsgi]
