#!/bin/bash

message0() { echo -e "\n\e[1;32m==>\e[1;33m $1\e[0;0m" ; }
message1() { echo -e "\e[1;32m==>\e[1;36m $1\e[0;0m" ; }

. "${BUILD_PYPKG27_CONF:-/etc/default/build-pypkg27.conf}"

export PATH=$PATH:$HOME/.local/bin

export PIP_CONFIG_FILE=/dev/null
export PIP_NO_CACHE_DIR=no
export PIP_DISABLE_PIP_VERSION_CHECK=yes
export PIP_ISOLATED=yes

message0 "checking requirements"
for dist in pip setuptools wheel virtualenv; do
    message1 "checking requirements: $dist"
    pip2 list --user | grep "$dist" &> /dev/null || { 
        message0 "Bootstrapping $dist" ;
        pip2 install --download "$WHLDIR" "$dist" ;
        pip2 install --no-index --find-links "$WHLDIR" --user --upgrade "$dist" ;
    }
done

for (( i=0 ; i < ${#DIST[*]} ; i++ )); do
    message0 "${DIST[i]}"

    message1 "${DIST[i]}: downloading wheel"
    pip2 install --download "$WHLDIR" "${DIST[i]}" \
        | egrep '^  (Downloading .+|File was already downloaded .+)$'
    #find "$WHLDIR/" -type f -not -name '*.whl' -exec mv -vf '{}' "$SRCDIR" ';'

    message1 "${DIST[i]}: downloading sdist"
    pip2 install --download "$SRCDIR" --no-use-wheel "${DIST[i]}" \
        | egrep '^  (Downloading .+|File was already downloaded .+)$'

    message1 "${DIST[i]}: building wheel"
    pip2 wheel --no-index --find-links "$SRCDIR" --find-links "$WHLDIR" --wheel-dir "$WHLDIR" "${DIST[i]}" \
        | egrep '^(Skipping .+, due to already being wheel\.|  Running setup\.py bdist_wheel for .+|Successfully built .+)$'
done

for (( i=0 ; i < ${#WHL_BLACKLIST[*]} ; i++ )); do
    message0 "${WHL_BLACKLIST[i]}: checking for blacklisted wheel"
    find "$WHLDIR/" -name "${WHL_BLACKLIST[i]}*.whl" -type f -exec rm -v '{}' ';'
done
