- name: "{{ name }} | install {{ pkg }}"
  pip: name={{ pkg }} virtualenv=/srv/{{ name }} state=present
  args:
    executable: /srv/{{ name }}/bin/pip
    virtualenv_command: /root/.local/bin/virtualenv
  notify:
  - "{{ name }} | restart services"
  tags: python2-app

- name: "{{ name }} | create user account"
  user: "name={{ name }} system=yes createhome=no groups=http home=/var/{{ name }} shell=/bin/false state=present"
  tags: python2-app

- name: "{{ name }} | create directories"
  file: name={{ item }} state=directory owner={{ name }} group={{ name }} mode=700
  with_items:
  - "/var/lib/{{ name }}"
  - "/etc/{{ name }}"
  tags: python2-app

- name: "{{ name }} | configure"
  template: src={{ item.src }} dest={{ item.dest }} owner={{ name }} group={{ name }} 
  with_items: cfg
  notify:
  - "{{ name }} | reload systemd units"
  - "{{ name }} | restart services"
  tags: python2-app

- name: "{{ name }} | enable services"
  service: name={{ item.name }} enabled=yes state={{ item.state }}
  with_items: enable
  notify:
  - "{{ name }} | restart services"
  tags: python2-app

- meta: flush_handlers
  tags: python2-app
