- name: "install mariadb"
  pacman: name={{ item }} state=present
  with_items:
  - mariadb
  - mariadb-clients
  notify: "restart mariadb"
  tags: mariadb

- name: "initial setup"
  shell: /usr/bin/mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
  args:
    creates: "/var/lib/mysql/mysql"
  notify: "restart mariadb"
  tags: mariadb

- meta: flush_handlers
