- name: install transmission
  pacman:
    name: transmission-cli
    state: installed
  notify: restart transmission
  tags: transmission

- name: configure transmission
  template:
    src: transmission.service.j2
    dest: /etc/systemd/system/transmission
    owner: root
    group: root
    mode: 0644
  notify:
  - reload systemd
  - restart transmission
  tags: transmission

- meta: flush_handlers
