
- name: "install fail2ban and ipset"
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
  - fail2ban
  - ipset
  notify: "restart firewall"
  tags: firewall

- name: "install firewall scripts"
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
  - { src: firewall,            dest: "/usr/local/sbin",        mode: "0700" }
  - { src: geoblocks,           dest: "/usr/local/sbin",        mode: "0700" }
  - { src: update-geoblocks,    dest: "/usr/local/sbin",        mode: "0700" }
  - { src: config,              dest: "/etc/default/firewall",  mode: "0600" }
  - { src: jail.conf,           dest: "/etc/fail2ban/jail.d",   mode: "0644" }
  - { src: firewall.target,     dest: "/etc/systemd/system",    mode: "0644" }
  - { src: firewall.service,    dest: "/etc/systemd/system",    mode: "0644" }
  - { src: fail2ban.service,    dest: "/etc/systemd/system",    mode: "0644" }
  notify: "restart firewall"
  tags: firewall

- name: "download and parse geoip database"
  shell: "/usr/local/sbin/update-geoblocks"
  args:
    creates: "/var/lib/firewall/geoblocks"
  notify: "restart firewall"
  tags: firewall

- name: "enable services"
  service:
    name: "{{ item }}"
    enabled: yes
  with_items:
  - fail2ban.service
  - firewall.service
  - firewall.target
  notify: "restart firewall"
  tags: firewall
