#
# postfix
#

- name: "install postfix etc"
  pacman: "name={{ item }} state=present"
  with_items:
  - postfix
  - postgrey
  - python2-postfix-policyd-spf
  - procmail
  tags: [email, postfix]

- name: "configure /etc/postfix/main.cf"
  template: src=main.cf.j2 dest=/etc/postfix/main.cf backup=yes
  notify: "restart postfix"
  tags: [email, postfix]

- name: "configure /etc/postfix/master.cf"
  lineinfile:
    dest: "/etc/postfix/master.cf"
    line: "{{ item }}"
  with_items:
    - "policy-spf unix - n n - - spawn user=nobody argv=/usr/bin/policyd-spf"
    - "465 inet n - n - - smtpd -o smtpd_tls_wrappermode=yes -o smtpd_sasl_auth_enable=yes"
  notify: "restart postfix"
  tags: [email, postfix]

- name: "configure /etc/postfix/aliases"
  lineinfile:
    dest: "/etc/postfix/aliases"
    line: "{{ item.name }}: {{ item.dest }}"
  with_items: postfix.aliases
  notify: "run postalias"
  tags: [email, postfix]

- name: "configure /etc/postfix/virtual"
  lineinfile:
    dest: "/etc/postfix/virtual" 
    line: "{{ item.domain }} {{ item.user }}"
  with_items: postfix.virtuals
  notify: "run postmap"
  tags: [email, postfix]

#
# dovecot
#

- name: "install dovecot"
  pacman: "name={{ item }} state=present"
  with_items:
  - dovecot
  tags: [email, dovecot]

- name: "configure dovecot users"
  template: "src={{ item.src }} dest={{ item.dest }}"
  with_items:
  - { src: users.j2, dest: /etc/dovecot/users }
  - { src: dovecot.conf.j2, dest: /etc/dovecot/dovecot.conf }
  notify: "restart dovecot"
  tags: [email, dovecot]

#
# mutt
#

- name: "install mutt"
  pacman: "name={{ item }} state=present"
  with_items:
  - mutt
  tags: [email, mutt]

- name: "install /etc/Muttrc"
  template: src=muttrc.j2 dest=/etc/Muttrc
  tags: [email, mutt]

#####

- meta: flush_handlers
  tags: [email, postfix, dovecot, mutt]

