- name: "check connection"
  ping:
  tags: arch-common

- name: "set hostname"
  hostname: 
  args:
    name: "{{ hostname }}"
  tags: arch-common

- name: "disable root login"
  shell: passwd -l root ; touch /root/.root-login-disabled 
  args:
    creates: /root/.root-login-disabled
  tags: arch-common

- name: "create users"
  user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
  with_items: users
  tags: arch-common

- name: "install rsync"
  pacman: 
    name: rsync
    state: installed
  tags: arch-common

- name: "add AUR repository"
  ini_file: 
    backup: yes
    dest: "/etc/pacman.conf"
    section: aur
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
  - { option: SigLevel, value: Never }
  - { option: Server, value: "{{ aur_url }}" }
  notify: "update pacman"
  tags: arch-common

- name: "flush handlers"
  meta: flush_handlers
  tags: arch-common
