- name: "check connection"
  ping:
  tags: arch-common

- name: "set hostname"
  hostname: 
  args:
    name: "{{ hostname }}"
  tags: arch-common

# name: "disable root login"
# shell: passwd -l root ; touch /root/.root-login-disabled 
# args:
#   creates: /root/.root-login-disabled
# tags: arch-common

- name: "create users"
  user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
  with_items: users
  tags: arch-common

- name: "install packages"
  pacman: 
    name: "{{ item }}"
    state: installed
  with_items: packages
  tags: arch-common

- name: "add Arch repo"
  ini_file: "backup=yes dest=/etc/pacman.conf section={{ item.name }} option=SigLevel value=Never"
  with_items: arch_repo
  notify: "update pacman"
  tags: arch-common

- name: "add Arch repo"
  ini_file: "backup=yes dest=/etc/pacman.conf section={{ item.name }} option=Server value={{ item.url }}"
  with_items: arch_repo
  notify: "update pacman"
  tags: arch-common

- name: "flush handlers"
  meta: flush_handlers
  tags: arch-common
