- name: "check connection"
  ping:
  tags: arch-common

- name: "set hostname"
  hostname: 
  args:
    name: "{{ hostname }}"
  tags: arch-common

- name: "create users"
  user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
  with_items: users
  tags: arch-common

- name: "set authorized keys"
  authorized_key:
    user: "{{ item.0.user}}"
    key: "{{ lookup('file', 'data/' + item.1) }}"
    state: present
    manage_dir: yes
  with_subelements: [ ssh, pubkeys ]
  tags: arch-common

- name: "install ssh config file"
  copy:
    src: ssh-config
    dest: "~{{ item.user }}/.ssh/config"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
  with_items: ssh
  tags: arch-common

- name: "install packages"
  pacman: 
    name: "{{ item }}"
    state: installed
  with_items: packages
  tags: arch-common

- name: "add Arch repo"
  ini_file: "backup=yes dest=/etc/pacman.conf section={{ item.name }} option=SigLevel value=Never"
  with_items: arch_repo
  notify: "update pacman"
  tags: arch-common

- name: "add Arch repo"
  ini_file: "backup=yes dest=/etc/pacman.conf section={{ item.name }} option=Server value={{ item.url }}"
  with_items: arch_repo
  notify: "update pacman"
  tags: arch-common

- name: "flush handlers"
  meta: flush_handlers
  tags: arch-common
