- name: "check connection"
  ping:
  tags: arch-common

- name: "set hostname"
  hostname: 
    name: "{{ ansible_hostname }}"
  tags: arch-common

- name: "create wheel group"
  group:
    name: wheel
    state: present
  tags: arch-common

- name: "create users"
  user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    groups: "{{ item.groups }}"
  with_items: users
  tags: arch-common

- name: "allow sudo to wheel users"
  lineinfile:
    line: "%wheel ALL=(ALL) ALL"
    dest: "/etc/sudoers.d/wheel"
    create: yes
  tags: arch-common

- name: "set authorized keys"
  authorized_key:
    user: "{{ item.0.user}}"
    key: "{{ ssh[item.1] }}"
    state: present
    manage_dir: yes
  with_subelements: [ authorized_keys, pubkeys ]
  tags: arch-common

- name: "install ssh config file"
  copy:
    src: ssh-config
    dest: "~{{ item.user }}/.ssh/config"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
  with_items: authorized_keys
  tags: arch-common

- name: "disable ssh password login"
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    line: "PasswordAuthentication no"
    regexp: "^#?PasswordAuthentication (?:yes|no)$"
  notify: "restart sshd"
  tags: arch-common

- name: "install packages"
  pacman: 
    name: "{{ item }}"
    state: installed
  with_items: packages
  tags: arch-common

- name: "flush handlers"
  meta: flush_handlers
  tags: arch-common
