- name: "install samba"
  pacman: "name=samba state=present"
  notify: "restart samba"
  tags: samba

- name: "configure samba"
  template: "src=smb.conf.j2 dest=/etc/samba/smb.conf"
  notify: "restart samba"
  tags: samba

- name: "flush handlers"
  meta: flush_handlers
  tags: samba


