#
# fstab
#

- name: "configure /etc/fstab"
  mount:
  args:
    src: "{{ item.dev }}"
    name: "{{ item.dir }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts }}"
    state: "mounted"
  with_items: fstab
  tags: [fileserver, fstab]

#
# samba
#

- name: "install samba"
  pacman: "name=samba state=present"
  notify: "restart samba"
  tags: [fileserver, samba]

- name: "configure samba"
  template: "src=smb.conf.j2 dest=/etc/samba/smb.conf"
  notify: "restart samba"
  tags: [fileserver, samba]

#
# nfs
#

- name: "install nfs-utils"
  pacman: "name=nfs-utils state=present"
  notify: "restart nfs"
  tags: [fileserver, nfs]

- name: "configure nfs"
  copy:
    src: "nfs-server.conf"
    dest: "/etc/conf.d"
  notify: "restart nfs"
  tags: [fileserver, nfs]

###

- name: "flush handlers"
  meta: flush_handlers
  tags: [fileserver, samba]

