#
# fstab
#

- name: "fstab | configure"
  mount:
  args:
    src: "{{ item.dev }}"
    name: "{{ item.dir }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts }}"
    state: "mounted"
  with_items: fstab
  tags: [fileserver, fstab]

#
# samba
#

- name: "samba | install"
  pacman: name=samba state=present
  notify: "samba | restart"
  tags: [fileserver, samba]

- name: "samba | configure"
  template: src=smb.conf.j2 dest=/etc/samba/smb.conf
  notify: "samba | restart"
  tags: [fileserver, samba]

- meta: flush_handlers
  tags: [fileserver, samba]

#
# nfs
#

- name: "nfs | install"
  pacman: name=nfs-utils state=present
  notify: "nfs | restart"
  tags: [fileserver, nfs]

- name: "nfs | configure daemons"
  copy: src={{ item }} dest=/etc/conf.d
  with_items:
  - nfs-server.conf
  - nfs-common.conf
  notify: "nfs | restart"
  tags: [fileserver, nfs]

- name: "nfs | configure exports"
  template: src=exports.j2 dest=/etc/exports
  notify: "nfs | restart"
  tags: [fileserver, nfs]

- meta: flush_handlers
  tags: [fileserver, nfs]

#
# cups
#

- name: "cups | install"
  pacman: name={{ item }} state=present
  with_items:
  - cups
  - ghostscript
  - gsfonts
  - hplip
  - python-dbus
  - python-gobject2
  - nss-mdns
  notify: "cups | restart"
  tags: [fileserver, cups]

- name: "cups | configure"
  template: src=cupsd.conf.j2 dest=/etc/cups/cupsd.conf
  notify: "cups | restart"
  tags: [fileserver, cups]

- meta: flush_handlers
  tags: [fileserver, cups]

#
# sane
#

# TODO
