#!/bin/bash -e

message "Partitioning" # 2048 sectors/MB, sda1: 256MB, sda2: the rest
sfdisk --quiet --unit S /dev/sda << EOF
$[1*2048],$[256*2048],L
$[257*2048],,L
EOF
sleep 3
partprobe /dev/sda
sleep 3

message "Formatting"
mkfs.btrfs --force --label "root" /dev/sda2
mkfs.ext4 -L "boot" /dev/sda1

message "Mounting"
mount /dev/sda2 /mnt
mkdir /mnt/boot
mount /dev/sda1 /mnt/boot

message "Bootstrapping"
pacstrap /mnt base btrfs-progs grub openssh python2 lsb-release

message "Generating /etc/fstab"
genfstab -L -p /mnt > /mnt/etc/fstab
