- name: "restart samba"
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
  - smbd.service
  - nmbd.service
  tags: [fileserver, samba]

- name: "restart nfs"
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
  - nfs-config
  - rpc-statd
  - nfs-server
  tags: [fileserver, nfs]
