- name: "samba | restart"
  service: name={{ item }} state=restarted enabled=true
  with_items:
  - smbd.service
  - nmbd.service
  tags: [fileserver, samba]

- name: "nfs | restart"
  service: name={{ item }} enabled=yes state=restarted
  with_items:
  - rpcbind.service
  - nfs-config.service
  - rpc-statd.service
  - nfs-server.service
  tags: [fileserver, nfs]

- name: "cups | restart"
  service: name={{ item }} state=restarted enabled=true
  with_items:
  - org.cups.cupsd.socket
  tags: [fileserver, cups]
