- name: "samba | restart"
  service: name={{ item }} state=restarted enabled=true
  with_items:
  - smbd.service
  - nmbd.service
  tags: [fileserver, samba]

- name: "nfs | restart"
  service: name={{ item }} enabled=yes state=restarted
  with_items:
  - nfs-config.service
  - rpcbind.service
  - rpc-statd.service
  - nfs-server.service
  tags: [fileserver, nfs]

- name: "cups | restart"
  service: name={{ item.svc }} state={{ item.state }} enabled=yes
  with_items:
  - { svc: org.cups.cupsd.socket, state: started }
  - { svc: org.cups.cupsd.service, state: restarted }
  tags: [fileserver, cups]
