- name: "samba | restart"
  service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  with_items:
  - smbd.service
  - nmbd.service
  tags: [fileserver, samba]

- name: "nfs | restart"
  service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  with_items:
  - nfs-config
  - rpc-statd
  - nfs-server
  tags: [fileserver, nfs]

- name: "cups | restart"
  service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  with_items:
  - cups.service
  tags: [fileserver, cups]
