ansible_ssh_host: 127.0.0.1
ansible_ssh_port: 60022
ansible_ssh_user: root
ansible_python_interpreter: /usr/bin/python2

hostname: arch-qemu

pysrc_url: http://10.0.2.2:8000/pypkg27/src/
pypkg_url: http://10.0.2.2:8000/pypkg27/archlinux
aur_url: http://10.0.2.2:8000/aur
