- name: "install bind9"
  apt: name={{ item }} state=present
  with_items:
  - bind9
  - bind9utils
  notify: "restart bind9"
  tags: [dns, dns-slave]

- name: "configure bind9"
  template: src=named.conf.local.j2 dest=/etc/bind/named.conf.local owner=root group=bind
  notify: "restart bind9"
  tags: [dns, dns-slave]

- name: "configure zones"
  template: src=named.conf.slave.j2 dest=/etc/bind/named.conf.{{ item }} owner=root group=bind
  with_items: zones
  notify: "reload bind9"
  tags: [dns, dns-slave]

- name: "allow port 53"
  ufw: name=Bind9 rule=allow
  notify: "restart ufw"
  tags: [dns, dns-slave]
